### ISSUE TITLE
Blur not working on Manjaro Gnome 3.36.6 X11

### ISSUE THREAD

**Issue by SuperZoops** [owozsh/Myopia-GTK#8]
If this is just a Wayland feature, please say so somewhere. Blur provider is enabled.

**Comment by owozsh** [comment]
Only for X11, I'll add it to the README file ;)

**Comment by SuperZoops** [comment]
Alright, I have no idea why it's not working, then.

**Comment by owozsh** [comment]
> Alright, I have no idea why it's not working, then.

did you select the window to apply the blur?

**Comment by SuperZoops** [comment]
I did everything I could that was stated in your "docs".

Also "This theme was only tested on Gnome 3.6+." 
Gnome 3.6 won't ever be released, as they're planning on jumping from 3.38 to 40. Fix the typo lol.

**Comment by owozsh** [comment]
omgggg I meant 3.36 XD thanks m8

**Comment by owozsh** [comment]
Sorry, but your issue is with blur provider.
